/******************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for TM4C123GH6PM Microcontroller - Port Driver
 *
 * Author: Toka Zakaria
 ******************************************************************************/

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION      (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION      (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION      (3U)

/* Port Pre-Compile Configuration Header file */
#include "Port.h"

/* AUTOSAR Version checking between Dio_PBcfg.c and Dio.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
		||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
		||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
#error "The AR version of Port.h does not match the expected version"
#endif

/* Software Version checking between Dio_PBcfg.c and Dio.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
		||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
		||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
#error "The SW version of Port.h does not match the expected version"
#endif


/* PB structure used with Port_Init API */
const Port_ConfigType Port_Configuration = 
{
		PORT_PIN_01, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_04, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR, 
		PORT_PIN_05, PORT_PIN_MODE_DIO, PORT_PIN_IN, INITIAL_VALUE, directionChangable_ON, modeChangable_ON, PULL_UP, 
		PORT_PIN_06, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_07, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR, 
		PORT_PIN_08, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR, 
		PORT_PIN_09, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_10, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR, 
		PORT_PIN_13, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR, 
		PORT_PIN_14, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_15, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_16, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_17, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_18, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_19, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_20, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_21, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_22, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_23, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_24, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_28, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_29, PORT_PIN_MODE_DIO, PORT_PIN_OUT, INITIAL_VALUE, directionChangable_ON, modeChangable_ON, OFF,
		PORT_PIN_30, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_31, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_43, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_44, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_45, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_46, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_47, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_48, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_49, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_50, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_51, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_52, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_53, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_57, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_58, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_59, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_60, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_61, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_62, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_63, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR,
		PORT_PIN_64, PORT_PIN_DEFAULT_MODE, PORT_PIN_DEFAULT_DIRECTION, PORT_PIN_DEFAULT_INITIAL_VALUE, PORT_PIN_DEFAULT_DIRECTION_CHANGEABLE, PORT_PIN_DEFAULT_MODE_CHANGEABLE, PORT_PIN_DEFAULT_INTERNAL_RESISTOR
};

